# Generated by Django 3.2.8 on 2021-10-05 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Вопрос')),
                ('answer', models.CharField(max_length=255, verbose_name='Ответ')),
                ('answer_option_one', models.CharField(max_length=255, verbose_name='Вариант ответа 1')),
                ('answer_option_two', models.CharField(max_length=255, verbose_name='Вариант ответа 2')),
                ('answer_option_third', models.CharField(max_length=255, verbose_name='Вариант ответа 3')),
                ('answer_option_four', models.CharField(max_length=255, verbose_name='Вариант ответа 4')),
            ],
            options={
                'verbose_name': 'Вопрос',
                'verbose_name_plural': 'Вопросы',
            },
        ),
        migrations.CreateModel(
            name='TelegramUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=255, verbose_name='Фамилия')),
                ('username', models.CharField(max_length=255, verbose_name='Имя пользователя')),
                ('telegram_id', models.IntegerField(verbose_name='Telegram ID')),
                ('true_answer', models.PositiveIntegerField(null=True, verbose_name='Правильных ответов')),
                ('false_answer', models.PositiveIntegerField(null=True, verbose_name='Неправильных ответов')),
                ('current_question', models.PositiveIntegerField(null=True, verbose_name='Текущий вопрос')),
            ],
            options={
                'verbose_name': 'Пользователь Telegram',
                'verbose_name_plural': 'Пользователи Telegram',
            },
        ),
    ]
