# Generated by Django 3.2.8 on 2021-10-05 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='questions',
            name='image',
            field=models.ImageField(null=True, upload_to='question_photos/'),
        ),
    ]
