# Generated by Django 3.2.8 on 2021-10-06 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0003_auto_20211007_0118'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegramuser',
            name='duration_game',
            field=models.CharField(max_length=255, null=True, verbose_name='Продолжительтельность игры'),
        ),
        migrations.AddField(
            model_name='telegramuser',
            name='start_game',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Начало викторины'),
        ),
        migrations.AlterField(
            model_name='telegramuser',
            name='status',
            field=models.CharField(choices=[('Авторизовался', 'Авторизовался'), ('Проходит викторину', 'Проходит викторину'), ('Закончил викторину', 'Закончил викторину')], default='Авторизовался', max_length=255, verbose_name='Статус'),
        ),
    ]
