# Generated by Django 3.2.8 on 2021-10-07 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0004_auto_20211007_0139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telegramuser',
            name='current_question',
            field=models.PositiveIntegerField(default=0, null=True, verbose_name='Текущий вопрос'),
        ),
        migrations.AlterField(
            model_name='telegramuser',
            name='false_answer',
            field=models.PositiveIntegerField(default=0, null=True, verbose_name='Неправильных ответов'),
        ),
        migrations.AlterField(
            model_name='telegramuser',
            name='true_answer',
            field=models.PositiveIntegerField(default=0, null=True, verbose_name='Правильных ответов'),
        ),
    ]
