# Generated by Django 3.2.8 on 2021-10-07 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0005_auto_20211007_1512'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telegramuser',
            name='current_question',
            field=models.PositiveIntegerField(default=0, verbose_name='Текущий вопрос'),
        ),
        migrations.AlterField(
            model_name='telegramuser',
            name='duration_game',
            field=models.CharField(default=0, max_length=255, verbose_name='Продолжительтельность игры'),
        ),
        migrations.AlterField(
            model_name='telegramuser',
            name='false_answer',
            field=models.PositiveIntegerField(default=0, verbose_name='Неправильных ответов'),
        ),
        migrations.AlterField(
            model_name='telegramuser',
            name='true_answer',
            field=models.PositiveIntegerField(default=0, verbose_name='Правильных ответов'),
        ),
    ]
